export class Volo {
  id: number;
  descrizione: string;
  idAereo: number;
  modello: string;
  marche: string;
  idPilota: number;
  nomePilota: string;
  cognomePilota: string;
  idPasseggero: number;
  nomePasseggero: string;
  cognomePasseggero: string;
  oraInizio: Date;
  orametroOreInizio: number;
  orametroMinutiInizio: number;
  oraFine: Date;
  orametroOreFine: number;
  orametroMinutiFine: number;
  durata: number;
  carburanteInizialeSx: number;
  carburanteInizialeDx: number;
  carburanteAggiuntoSx: number;
  carburanteAggiuntoDx: number;
  olio: number;
  idAeroportoInizio: number;
  aeroportoInizio: string;
  idAeroportoFine: number;
  aeroportoFine: string;
}
